export type ConfluencePage = {
  id: string;
  title: string;
  space: string;
  labels: string[];
  updated: string;
  body: string[];
};

export const confluenceSpace = {
  key: "PORTFOLIO",
  name: "Portfolio Documentation",
  description:
    "Living documentation for the Cristhian Alcocer portfolio site: architecture, QA strategy, Tools lab and release notes.",
};

export const confluencePages: ConfluencePage[] = [
  {
    id: "home",
    title: "Home",
    space: "PORTFOLIO",
    labels: ["overview"],
    updated: "2026-07-27",
    body: [
      "Welcome to the Portfolio Documentation space.",
      "This Confluence simulation captures architecture, QA strategy, security posture, Tools lab demos and release notes for https://cristhianalcoceririarte.github.io/cristhian-alcocer-portfolio/.",
      "Use the left sidebar to browse pages. Content mirrors the live site so hiring managers can see how QA artifacts and delivery docs are organized.",
      "Owner: Cristhian Alcocer Iriarte · Role: QA Lead & Senior QA Engineer · Location: Cochabamba, Bolivia.",
    ],
  },
  {
    id: "architecture",
    title: "Architecture",
    space: "PORTFOLIO",
    labels: ["engineering"],
    updated: "2026-07-27",
    body: [
      "Stack: Next.js (App Router) + TypeScript + Tailwind CSS + Framer Motion.",
      "Deployment: static export (output: export) to GitHub Pages with basePath /cristhian-alcocer-portfolio.",
      "Content source of truth: src/lib/content.ts. Live E2E assertions: src/lib/live-suite.ts. Security policy: src/lib/security.ts.",
      "Routes: / (homepage sections) and /tools (QA tooling simulations).",
      "Navigation: Next.js Link with hash targets so section jumps from /tools keep the GitHub Pages basePath.",
      "Quality gate: Playwright e2e suite (exactly 9 tests) runs in GitHub Actions before Pages deploy.",
    ],
  },
  {
    id: "tools-lab",
    title: "Tools Lab",
    space: "PORTFOLIO",
    labels: ["tools", "demo"],
    updated: "2026-07-27",
    body: [
      "Route: /tools - interactive simulations seeded with real portfolio data.",
      "Tab order: Confluence, Jira, SQL, Postman, Playwright, JMeter, Fiddler, WCAG, Kafka.",
      "Confluence - this documentation space (architecture, strategy, releases, contracts).",
      "Jira - Epic PORT-1, stories, 9 test cases (PORT-10..PORT-18) and executions mapped to Playwright.",
      "SQL - in-memory portfolio_db with SELECT / WHERE / ORDER BY / LIMIT / SHOW / DESCRIBE (LIKE patterns are regex-safe).",
      "Postman - mock REST collection for profile, experience, skills, metrics and contact.",
      "Playwright - live runner against a homepage iframe preview; run one test, a selection, or the full suite of 9.",
      "JMeter - load plan against the same mock APIs (users, loops, samplers).",
      "Fiddler - HTTP(S) session capture of homepage, Tools, APIs, fonts and WhatsApp redirect.",
      "WCAG - section checks plus axe-core against the live homepage preview.",
      "Kafka - topics for page views, contact messages, QA results and Tools audit events.",
    ],
  },
  {
    id: "test-strategy",
    title: "Test Strategy",
    space: "PORTFOLIO",
    labels: ["qa", "strategy"],
    updated: "2026-07-27",
    body: [
      "Approach: Shift-Left content review + risk-based smoke coverage + live demonstration of tooling fluency.",
      "Automated suite: e2e/portfolio.spec.ts contains exactly 9 Playwright test cases (Chromium).",
      "CI: GitHub Actions builds the static export, serves out/, runs Playwright 9/9, then deploys Pages.",
      "Live runners: homepage FAB (full suite) and Tools > Playwright (individual, selected, or all).",
      "Jira mapping: Epic PORT-1 -> Stories PORT-2/3/4 -> Test Cases PORT-10..PORT-18 (TC-01..TC-09) -> Test Executions PORT-20/21/22.",
      "Coverage layers:",
      "1) Content integrity (LinkedIn-aligned experience, contact channels, open-to-work messaging).",
      "2) UI smoke (hero, navigation, section reachability).",
      "3) Contact form controls and input acceptance.",
      "4) Accessibility basics (skip link, document title) plus WCAG lab for deeper checks.",
      "5) Tools lab demos for Postman, Playwright, JMeter, Jira, Confluence, SQL, Fiddler, WCAG and Kafka.",
      "Environments: localhost:3000 (dev), static out/ (CI), GitHub Pages (prod).",
    ],
  },
  {
    id: "security",
    title: "Security",
    space: "PORTFOLIO",
    labels: ["security"],
    updated: "2026-07-27",
    body: [
      "Surface: static site with no backend database or shell. User inputs are the contact mailto form and client-side Tools simulations.",
      "XSS posture: no dangerouslySetInnerHTML / eval / innerHTML sinks; React text escaping for form and SQL output.",
      "Contact: name, email and message are encodeURIComponent'd into mailto subject/body; destination email is a static constant.",
      "SQL Lab: client-only subset (SELECT/SHOW/DESCRIBE). LIKE wildcards escape RegExp metacharacters to prevent regex injection / ReDoS.",
      "Defense in depth: production HTML embeds Content-Security-Policy and Referrer-Policy (src/lib/security.ts).",
      "CSP allows 'self' plus unsafe-inline for App Router hydration and Tailwind; form-action includes mailto:; object-src none.",
      "public/_headers adds X-Content-Type-Options, X-Frame-Options DENY, Permissions-Policy and COOP for Cloudflare/Netlify hosts (GitHub Pages ignores custom headers).",
      "Hash navigation uses getElementById (not raw querySelector) to avoid selector injection from the URL fragment.",
    ],
  },
  {
    id: "release-notes",
    title: "Release Notes",
    space: "PORTFOLIO",
    labels: ["release"],
    updated: "2026-07-27",
    body: [
      "v1.0 - Next.js portfolio rebuild with amber dark theme and Playwright runner.",
      "v1.1 - LinkedIn content alignment, WhatsApp contact link, spacing polish.",
      "v1.2 - Tools lab: Postman collection, JMeter plan, Jira QA project, Confluence docs, SQL console.",
      "v1.3 - WCAG audit lab with section checks and axe-core against the live homepage preview.",
      "v1.4 - Kafka lab with portfolio topics, produce/consume flows and message inspection.",
      "v1.5 - Fiddler lab for HTTP(S) traffic capture; Tools tab order: Confluence, Jira, SQL, Postman, JMeter, Fiddler, WCAG, Kafka.",
      "v1.6 - Contact section reorganized (labeled channels + form); footer All rights reserved; SQL LIKE hardening; CSP + _headers defense in depth.",
      "v1.7 - Playwright Tools lab after Postman: run individual tests, selected sets, or the full 9-case suite against a homepage iframe preview.",
    ],
  },
  {
    id: "api-contracts",
    title: "API Contracts (Mock)",
    space: "PORTFOLIO",
    labels: ["api"],
    updated: "2026-07-27",
    body: [
      "The Postman / JMeter / Fiddler simulations share the same in-browser mock REST surface (no network backend on the static export):",
      "GET /api/health - service health",
      "GET /api/profile - public profile payload",
      "GET /api/experience - roles timeline",
      "GET /api/experience/current - current role only (NICE CXone)",
      "GET /api/expertise - expertise areas",
      "GET /api/skills - skills + languages",
      "GET /api/education - education record",
      "GET /api/metrics - portfolio metrics",
      "POST /api/contact - contact form simulation (requires name, email, message); returns mailto-simulated delivery metadata",
    ],
  },
  {
    id: "data-model",
    title: "Data Model",
    space: "PORTFOLIO",
    labels: ["sql", "data"],
    updated: "2026-07-27",
    body: [
      "SQL lab tables (seeded from src/lib/content.ts and jira-data):",
      "profiles - single-row profile identity",
      "experiences - professional roles",
      "experience_highlights - achievement bullets per role",
      "expertise_areas - capability cards",
      "skills - competency catalog",
      "education - academic record",
      "contact_messages - simulated inbound messages",
      "jira_issues - QA backlog mirror",
      "Supported SQL: SELECT ... FROM table [WHERE ...] [ORDER BY ...] [LIMIT n], SHOW TABLES, DESCRIBE table.",
      "Suggested query: SELECT company, title, period FROM experiences WHERE current = true;",
    ],
  },
  {
    id: "contact",
    title: "Contact & Hiring",
    space: "PORTFOLIO",
    labels: ["hiring", "contact"],
    updated: "2026-07-27",
    body: [
      "Section: Let's connect (#contact) - dual layout with labeled channels and Send a message form.",
      "Channels: Email (mailto), WhatsApp (wa.me), Location (Cochabamba, Bolivia), LinkedIn profile.",
      "Form fields: Full name, Email address, Message - submit opens the visitor's email client with a prefilled inquiry.",
      "Open to work: Quality Control Engineer and QA leadership roles.",
      "Footer: © 2026 Cristhian Alcocer Iriarte. All rights reserved.",
    ],
  },
];
